Sports/Controllers/CoachController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sports.Models;

namespace Sports.Controllers
{

    public class CoachController : Controller
    {
        private SportsEntities db = new SportsEntities();
        // GET: Coach
        public ActionResult Index(string firstname = "",string lastname = "")
        {

            var _coach = db.tbl_coach.Where(x => x.firstname.Contains(firstname) && x.lastname.Contains(lastname)).OrderByDescending(a => a.coach_id).ToList();

            
            return View(_coach);
        }

        public ActionResult Create()
        {

            return View();
        }

        //
 


        [HttpPost]
        public JsonResult Create(tbl_coach coach)
        {



            try
            {
                var coach_exist = db.tbl_coach.Where(x => x.firstname.ToLower().Trim() == coach.firstname.ToLower() && x.lastname.ToLower().Trim() == coach.lastname.ToLower()).Count();

                if (coach_exist > 0)
                {


                    return Json(new { message = "" + coach.firstname + " " + coach.lastname + " is already exist!", success = false, first = coach.firstname, last = coach.lastname }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    coach.created_date = DateTime.Now;
                    db.tbl_coach.Add(coach);

                    db.SaveChanges();
                    return Json(new { message = ""+ coach.firstname + " " + coach.lastname + " successfully inserted!", success = true, first = coach.firstname, last = coach.lastname }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { message = ex.Message, success = false, first = coach.firstname, last = coach.lastname }, JsonRequestBehavior.AllowGet);
            }




        }


        public ActionResult Delete()
        {

            return View();
        }

        //



        [HttpPost]
        public JsonResult Delete(string id= "")
        {

            int _id = Convert.ToInt32(id);

            var _exist = db.tbl_coach.Where(x => x.coach_id == _id).SingleOrDefault();
            var exist_team = db.tbl_teams.Where(x => x.coach_id == _id).Count();
            if (_exist == null)
            {
       
                return Json(new { message = " "+ _id + " not found!", success = false }, JsonRequestBehavior.AllowGet);
            }
            else if (exist_team > 0)
            {
                return Json(new { message = "Coach " + _exist.firstname + " " + _exist.lastname + " is not allowed to be deleted, this coach connected to the team", success = false }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                db.tbl_coach.Remove(_exist);
                db.SaveChanges();
                return Json(new { message = "" + _exist.firstname + " " + _exist.lastname + " successfully deleted!", success = true }, JsonRequestBehavior.AllowGet);
            }
       
        }





        public ActionResult Edit(int coach_id = 0)
        {
            var selected_coach = db.tbl_coach.Where(x => x.coach_id == coach_id).SingleOrDefault();

            if(selected_coach == null)
            {
                return HttpNotFound();
            }

          
            return View(selected_coach);
        }

        //



        [HttpPost]
        public ActionResult Edit(tbl_coach coach)
        {
            try {
                var check_name = db.tbl_coach.Where( x => x.firstname.ToLower() == coach.firstname.ToLower() && x.lastname.ToLower() == coach.lastname.ToLower()).Count();

                if(check_name > 0)
                {
                    return Json(new { message = "" + coach.firstname + " " + coach.lastname + " already exist!", success = false }, JsonRequestBehavior.AllowGet);
                }
                else
                { 
                coach.created_date = Convert.ToDateTime(coach.created_date);
                coach.updated_date = DateTime.Now;
                coach.coach_id = Convert.ToInt32(coach.coach_id);
         db.Entry(coach).State = EntityState.Modified;
           db.SaveChanges();
            return Json(new { message = "" + coach.firstname + " " + coach.lastname + " successfully updated!", success = true }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { message = ex.Message, success = false }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Details(int coach_id = 0)
        {
            var selected_coach = db.tbl_coach.Where(x => x.coach_id == coach_id).SingleOrDefault();

            if (selected_coach == null)
            {
                return HttpNotFound();
            }


            return View(selected_coach);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sports/Views/Coach/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="adminx-content">
    <div class="adminx-main-content">
        <div class="container-fluid">
            @using (Html.BeginForm())

            {




                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Create Coach</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <table class="table">

                                    <tbody>
                                        <tr>
                                            <td>
                                                <table class="table table-bordered">



                                                    <tr>
                                                        <td>
                                                            Firstname:
                                                        </td>
                                                        <td>

                                                            <input id="firstname" type="text" name="firstname" class="form-control" style="width: 400px;" maxlength="25"  />
                                                        </td>

                                                    </tr>


                                                    <tr>
                                                        <td>
                                                            Lastname:
                                                        </td>
                                                        <td>

                                                            <input id="lastname" type="text" name="lastname" class="form-control" style="width: 400px;" maxlength="25"  />
                                                        </td>

                                                    </tr>
                          

                                                </table>


                                            </td>

                                        </tr>

                                    </tbody>
                                </table>

                            </td>
                        </tr>

                    </tbody>
                    <tr>
                        <td>

                            <input type="button" id="btnSubmit" name="btnSubmit" value="Submit" class="btn btn-secondary float-right" />
                        </td>
                    </tr>



                </table>


                @Html.ActionLink("Back to List", "Index")

            }
        </div>
    </div>
</div>


<script type="text/javascript">

    $(document).ready(function () {

        $("#btnSubmit").click(function () {
            var coach = {}
            coach.firstname = $("#firstname").val().trim();
            coach.lastname = $("#lastname").val().trim();

            if (coach.firstname == "" && coach.lastname == "") {
                if (!$("#invalid").length) {
                    $('#firstname').before('<span class="form-label is-invalid" id="invalid" name="invalid" >Please enter a firstname</span>');
                }
                if (!$("#invalid1").length) {
                    $('#lastname').before('<span class="form-label is-invalid" id="invalid1" name="invalid1" >Please enter a lastname</span>');
                }
                    $("#firstname").attr('class', 'form-control is-invalid');
                $("#lastname").attr('class', 'form-control is-invalid');
            }
            else if (coach.firstname == "") {
                if (!$("#invalid").length) {
                    $('#firstname').before('<span class="form-label is-invalid" id="invalid" name="invalid" >Please enter a firstname</span>');
                }
                $("#invalid1").remove();
                $("#lastname").attr('class', 'form-control');
                $("#firstname").attr('class', 'form-control is-invalid');
            }
            else if (coach.lastname == "") {
                if (!$("#invalid1").length) {
                    $('#lastname').before('<span class="form-label is-invalid" id="invalid1" name="invalid1" >Please enter a lastname</span>');
                }
                $("#invalid").remove();
                $("#firstname").attr('class', 'form-control');
                $("#lastname").attr('class', 'form-control is-invalid');
            }
            else {

                $.ajax(
                    {
                        type: "POST", //HTTP POST Method
                        url: "/Coach/Create", // Controller/View
                        data: '{coach: ' + JSON.stringify(coach) + '}',
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {

                            if (data.success == true) {

                                //     $("span").addAttr("hidden");
                                $("#invalid").remove();
                                $("#invalid1").remove();
                                //    $("#name").addClass("form-control");
                                $("#firstname").attr('class', 'form-control');
                                $("#lastname").attr('class', 'form-control');
                                $('#firstname').val("");
                                $('#lastname').val("");
                                alert(''+data.message+'');
                            }

                            else {
                                if (!$("#invalid").length) {
                                    $('#firstname').before('<span class="form-label is-invalid" id="invalid" name="invalid" >' + data.first + ' already exist!</span>');
                                }
                                if (!$("#invalid1").length) {
                                    $('#lastname').before('<span class="form-label is-invalid" id="invalid1" name="invalid1" >' + data.last + ' already exist!</span>');
                                }
                                $("#firstname").attr('class', 'form-control is-invalid');
                                $("#lastname").attr('class', 'form-control is-invalid');

                            }
                        }

                  
                    })
            }
        })
    });


</script>

Sports/Views/Coach/Details.cshtml
@model Sports.Models.tbl_coach

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="adminx-content">
    <div class="adminx-main-content">
        <div class="container-fluid">
            @using (Html.BeginForm())

            {

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Coach Details</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <table class="table">

                                    <tbody>
                                        <tr>
                                            <td>
                                                <table class="table table-bordered">

                                                    <tr>
                                                        <td>
                                                            Id:
                                                        </td>
                                                        <td>

                                                            <input id="coach_id" value="@Model.coach_id" type="text" name="coach_id" class="form-control" style="width: 400px;" maxlength="25" disabled />
                                                        </td>

                                                    </tr>

                                                    <tr>
                                                        <td>
                                                            Firstname:
                                                        </td>
                                                        <td>

                                                            <input id="firstname" value="@Model.firstname" type="text" name="firstname" class="form-control" style="width: 400px;" maxlength="25" disabled />
                                                        </td>

                                                    </tr>


                                                    <tr>
                                                        <td>
                                                            Lastname:
                                                        </td>
                                                        <td>

                                                            <input id="lastname" type="text" value="@Model.lastname" name="lastname" class="form-control" style="width: 400px;" maxlength="25" disabled />
                                                        </td>

                                                    </tr>

                                                    <tr>
                                                        <td>
                                                            Created Date:
                                                        </td>
                                                        <td>

                                                            <input id="created_date" type="text" value="@Model.created_date" name="created_date" class="form-control" style="width: 400px;" maxlength="25" disabled />
                                                        </td>

                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            Updated Date:
                                                        </td>
                                                        <td>

                                                            <input id="updated_date" type="text" value="@Model.updated_date" name="updated_date" class="form-control" style="width: 400px;" maxlength="25" disabled />
                                                        </td>

                                                    </tr>
                                                </table>


                                            </td>

                                        </tr>

                                    </tbody>
                                </table>

                            </td>
                        </tr>

                    </tbody>
            


                </table>


                @Html.ActionLink("Back to List", "Index")

            }
        </div>
    </div>
</div>

Sports/Views/Coach/Edit.cshtml
@model Sports.Models.tbl_coach
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="adminx-content">
    <div class="adminx-main-content">
        <div class="container-fluid">
            @using (Html.BeginForm())

            {

                <input type="hidden" value="@Model.coach_id" id="coach_id" name="coach_id" />
                <input type="hidden" value="@Model.created_date" id="created_date" name="created_date" />

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Edit Coach</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <table class="table">

                                    <tbody>
                                        <tr>
                                            <td>
                                                <table class="table table-bordered">



                                                    <tr>
                                                        <td>
                                                            Firstname:
                                                        </td>
                                                        <td>

                                                            <input id="firstname" value="@Model.firstname" type="text" name="firstname" class="form-control" style="width: 400px;" maxlength="25" />
                                                        </td>

                                                    </tr>


                                                    <tr>
                                                        <td>
                                                            Lastname:
                                                        </td>
                                                        <td>

                                                            <input id="lastname" type="text" value="@Model.lastname" name="lastname" class="form-control" style="width: 400px;" maxlength="25" />
                                                        </td>

                                                    </tr>


                                                </table>


                                            </td>

                                        </tr>

                                    </tbody>
                                </table>

                            </td>
                        </tr>

                    </tbody>
                    <tr>
                        <td>

                            <input type="button" id="btnUpdate" name="btnUpdate" value="Update" class="btn btn-primary float-right" />
                        </td>
                    </tr>



                </table>


                @Html.ActionLink("Back to List", "Index")

            }
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {

        $("#btnUpdate").click(function () {
            var coach = {}
            coach.coach_id = $("#coach_id").val();
            coach.firstname = $("#firstname").val().trim();
            coach.lastname = $("#lastname").val().trim();
            coach.created_date = $("#created_date").val().trim();
            if (coach.firstname == "" && coach.lastname == "") {
                if (!$("#invalid").length) { // check if invalid not exist in form
                    $('#firstname').before('<span class="form-label is-invalid" id="invalid" name="invalid" >Please enter a firstname</span>');
                }
                if (!$("#invalid1").length) {// check if invalid1 not exist in form
                    $('#lastname').before('<span class="form-label is-invalid" id="invalid1" name="invalid1" >Please enter a lastname</span>');
                }
                $("#firstname").attr('class', 'form-control is-invalid');
                $("#lastname").attr('class', 'form-control is-invalid');
            }
            else if (coach.firstname == "") {
                if (!$("#invalid").length) {
                    $('#firstname').before('<span class="form-label is-invalid" id="invalid" name="invalid" >Please enter a firstname</span>');
                }
                $("#invalid1").remove();
                $("#lastname").attr('class', 'form-control');
                $("#firstname").attr('class', 'form-control is-invalid');
            }
            else if (coach.lastname == "") {
                if (!$("#invalid1").length) {
                    $('#lastname').before('<span class="form-label is-invalid" id="invalid1" name="invalid1" >Please enter a lastname</span>');
                }
                $("#invalid").remove();
                $("#firstname").attr('class', 'form-control');
                $("#lastname").attr('class', 'form-control is-invalid');
            }
            else {

                $.ajax(
                    {
                        type: "POST", //HTTP POST Method
                        url: "/Coach/Edit", // Controller/View
                        data: '{coach: ' + JSON.stringify(coach) + '}',
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {

                            if (data.success == true) {

                     
                                alert('' + data.message + '');
                                location.href = '/Coach/Index'
                            }

                            else {
                                alert('' + data.message + '');

                            }
                        }


                    })
            }
        })
    });


</script>

Sports/Views/Coach/Index.cshtml
@model IList<Sports.Models.tbl_coach>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="adminx-content">
    <div class="adminx-main-content">
        <div class="container-fluid">


            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">List of Coach</th>
                    </tr>
                </thead>
                <tr>
                    <td>
                        <table class="table">


                            <tbody>
                                <tr>
                                    <td>
                                        @Html.ActionLink("Create New", "Create", new { @class = "btn btn-link" })
                                    </td>

                                    @using (Html.BeginForm("Index", "Coach", FormMethod.Get))
                                    {
                                        <td>
                                            <h5>Firstname:</h5>
                                        </td>
                                        <td><input id="firstname" type="text" name="firstname" class="form-control" /></td>
                                        <td>
                                            <h5>Lastname:</h5>
                                        </td>
                                        <td><input id="lastname" type="text" name="lastname" class="form-control" /></td>


                                        <td>
                                            <input type="submit" name="go" value="Go" , new {@class="btn btn-primary" } />
                                        </td>
                                    }
                                </tr>
                            </tbody>
                        </table>
                        <div style="margin-top: 5px;margin-bottom: 5px">
                            <table class="table table-bordered" id="data-table">
                                <thead>
                                    <tr>

                                        <th>
                                            Id
                                        </th>
                                        <th>
                                            Firstname
                                        </th>
                                        <th>
                                            Lastname
                                        </th>
                                        <th>
                                            Created Date
                                        </th>

                                        <th>
                                            Updated Date
                                        </th>


                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.coach_id)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.firstname)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.lastname)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.created_date)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.updated_date)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", new { coach_id = item.coach_id }, new { @class = "btn btn-sm btn-primary" })
                                                @Html.ActionLink("Details", "Details", new { coach_id = item.coach_id }, new { @class = "btn btn-sm btn-success" })
                                                <input type="button" id="delete" name="delete" value="Delete" class="btn btn-sm btn-danger" onclick="Delete('@item.coach_id')" />
                                            </td>
                                        </tr>
                                    }
                                </tbody>


                                <tr>
                                </tr>
                            </table>
                        </div>
                    </td>
                </tr>

            </table>




        </div>

    </div>

</div>





@section scripts{



    <script type="text/javascript">
        function Delete(_value) {

            var _check = confirm('Do you want to delete this coach?');
            if (_check) {
                $.ajax(
                    {
                        type: "POST", //HTTP POST Method
                        url: "/Coach/Delete", // Controller/View
                        data: {
                            id: _value
                        },
                        success: function (data) {
                            if (data.success == false) {
                                alert(data.message);
                            }
                            else {
                                alert(data.message);
                                location.reload();
                            }

                        }


                    })
            } else {
                return false;
            }
        }
        $(document).ready(function () {


            $('#data-table').DataTable(
                {
                    searching: false,
                    lengthChange: true,
                    lengthMenu: [5, 10, 25, 50, 100],
                    sorting: true


                }
            );

         

        });
    </script>
}